### ISSUE TITLE
Points are too large in bqplot viewer by default

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-jupyter#13]
The points are too large in the bqplot scatter plots:

<img width="613" alt="screen shot 2018-08-26 at 13 08 28" src="https://user-images.githubusercontent.com/314716/44630818-90a4a100-a931-11e8-82c9-8d7e709295b0.png">

With scale = 0.1:

<img width="644" alt="screen shot 2018-08-26 at 13 11 56" src="https://user-images.githubusercontent.com/314716/44630824-a2864400-a931-11e8-9d4e-3f9cef2794ed.png">

**Comment by maartenbreddels** [comment]
This needs to be solved in bqplot, I need to match the code for the normal scatter sizes. Currently the diameter at least scales as sqrt(size) vs linear.
