### ISSUE TITLE
Expose circular selection in glupyter

### ISSUE THREAD

**Issue by eteq** [glue-viz/glue-jupyter#156]
While the machinery for circular selection is available in glue-core and qt-glue, it's not yet exposed in glue-jupyter.  This should be implemented.

To give a specific use case to work around: it would be useful to be able to make a circular selection in an image viewer of a data cube, and have the selected pixels be shown in a profile viewer for the same dataset. There should *also* be a way to extract that selection as a `regions` object so that a notebook workflow can continue from there and do a more complicated sum or whatever.

**Comment by astrofrog** [comment]
Done in #165
