### ISSUE TITLE
binder fails due to incorrect nodejs version

### ISSUE THREAD

**Issue by ianhi** [glue-viz/glue-jupyter#186]
**Describe the bug**

The current binder link in the readme resulted in this build error for me:

![image](https://user-images.githubusercontent.com/10111092/82010703-d5f68e00-9640-11ea-8546-298a9bd3daca.png)

**To Reproduce**
Go to: https://mybinder.org/v2/gh/glue-viz/glue-jupyter/master?filepath=notebooks

**Relevant Code**
Looks like this line needs an update:
https://github.com/glue-viz/glue-jupyter/blob/227089c802b131d1929f40137934eb5aeb45fb2a/binder/Dockerfile#L12

**Comment by astrofrog** [comment]
Thanks for the report!
