### ISSUE TITLE
Elliptical shape seems allowed in bqplot backend but not really

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-jupyter#223]
**Describe the bug**

This implies you support elliptical shape:

https://github.com/glue-viz/glue-jupyter/blob/12f4b2f211f53009dc76b822ba5af7e8db75ebd8/glue_jupyter/bqplot/common/tools.py#L190

But when I use `bqplot:circle` tool over at Jdaviz (Imviz), I can only draw circle.

**Expected behavior**

Not sure what the expectation should be. This is related to spacetelescope/jdaviz#518 , so might need inputs from @eteq et al.

**Comment by pllim** [comment]
The real problem is downstream at glue-viz/glue-astronomy#31

**Comment by javerbukh** [comment]
Are you sure it is downstream? I do not know for sure, but it looks like [this line](https://github.com/glue-viz/glue-jupyter/blob/master/glue_jupyter/bqplot/common/tools.py#L148) is preventing the ROI selector from forming an elliptical shape, forcing a circular shape instead. Can you comment on this @astrofrog or @maartenbreddels ?

**Comment by pllim** [comment]
OK, I'll reopen.

**Comment by pllim** [comment]
This test suggests that it is possible here already. 🤷 

https://github.com/glue-viz/glue-jupyter/blob/b28aab8bdf1d46e2d14115c1c73c08e912330e94/glue_jupyter/bqplot/tests/test_bqplot.py#L268-L284

**Comment by javerbukh** [comment]
I'm attaching a gif that shows ROI selector does not use accurate positions for either the x or y axis, depending on which is the shorter side.

![Jun-15-2021 11-03-52](https://user-images.githubusercontent.com/7179333/122077676-ee982100-cdc9-11eb-96fa-2b57bee2340b.gif)

And a screenshot of the end.

<img width="1007" alt="Screen Shot 2021-06-15 at 11 04 37 AM" src="https://user-images.githubusercontent.com/7179333/122077823-125b6700-cdca-11eb-913c-2d18fcbe0630.png">

The numbers after 'text' `[239.52512 412.06836] [431.0795  258.53625]` are the x and y positions of the interact `selected_x` and `selected_y`. These numbers are not accurate based on my final mouse positions. 

Is this a problem with the `BrushEllipseSelector`, or is it actually a problem in the `glue-astronomy` / `jdaviz` layer?

**Comment by pllim** [comment]
When you say not accurate, how much is the offset? What were the expected values?

**Comment by javerbukh** [comment]
For x about `[300 325]`.  The offset is caused by the diameter of the larger axis (y in this case) overriding the actual values of the x-axis.

**Comment by maartenbreddels** [comment]
`selected_x` and `selected_y` are the bounding box of the ellipse, does that make sense?

**Comment by javerbukh** [comment]
Yes, but `selected_x` in this case is not correct based on my mouse position when creating the ellipse.

**Comment by astrofrog** [comment]
Isn't this because we contraint the aspect ratio to 1? (That is if you take any vector graphics package and try and draw a circle by using an ellipse tool and eg pressing shift to constrain the aspect ratio, the mouse won't end up on the edge of the circle but will be floating in empty space). What happens if you remove the pixel_aspect kwarg?

I think we probably need to create a new class in glue-jupyter for elliptical selections that would be very similar to the circular one but without the pixel_aspect option and with slightly tweaked ROI logic (we should make sure we minimise duplicate code)

**Comment by pllim** [comment]
@astrofrog , if ellipse is currently not possible, what is the test in https://github.com/glue-viz/glue-jupyter/issues/223#issuecomment-859625379 actually testing?
