### ISSUE TITLE
Calling apply_roi multiple times overwrites the same Subset

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-jupyter#253]
Trying to write a test calling `viewer.apply_roi()` directly multiple times but it has surprising behavior, at least to me.

```python
from glue.core.roi import CircularROI, EllipticalROI, RectangularROI

# viewer is a bqplot image viewer from this package
viewer.apply_roi(CircularROI(xc=3, yc=4.5, radius=2.1))
viewer.apply_roi(EllipticalROI(xc=0, yc=5, radius_x=3, radius_y=3.5))
viewer.apply_roi(RectangularROI(xmin=1, xmax=11, ymin=2.5, ymax=4))
```

When I extract all the subsets, I expect to find 3, but I only found "Subset 1" that is populated with `RectangularROI`, which was the last shape I provided.

Multiple subsets get populated properly when I do the following but I thought `apply_roi` does the same thing.

https://github.com/glue-viz/glue-jupyter/blob/75ccfdfb9411c698131d7027bdb17fb748768e7f/glue_jupyter/bqplot/tests/test_bqplot.py#L273-L277

**Comment by astrofrog** [comment]
This is normal and is by design - the default mode in glue is to replace the subset unless 'create new' is selected in the edit subset mode.

**Comment by pllim** [comment]
Is there a programmatic way to tell it to create new without having to mess with the tool bar?

**Comment by astrofrog** [comment]
```viewer.session.edit_subset_mode.edit_subset = []``` - means no subsets are being edited so a new one should be created

**Comment by pllim** [comment]
Thanks!

**Comment by pllim** [comment]
Hmm... How do you re-enable the old behavior after you call `viewer.session.edit_subset_mode.edit_subset = []` and does something?
