### ISSUE TITLE
Set up JupyterLab on binder

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-jupyter#26]
This is just a reminder that we should investigate at some point how to set up JupyterLab on binder so as to be able to demo glue-jupyter.

**Comment by hcferguson** [comment]
demo_gaussian is linked to demo_image

demo_image uses files in the user's home directory. I thought it might be generating images on the fly :(

**Comment by astrofrog** [comment]
Done - the links in the README now use Jupyter Lab
