### ISSUE TITLE
Subset color indicators don't update after changing subset layer color

### ISSUE THREAD

**Issue by rosteen** [glue-viz/glue-jupyter#278]
**Describe the bug**
After changing a subset's color in the `Layer` options, the other locations that indicate a subset's color (in the `Layer` menu and the top level `Subset` selection menu) do not update until another subset is created. There may be other ways to trigger the update, but that's the first one I found. 

**Expected behavior**
All relevant subset menus show the correct color for a subset. 

**Screenshots**
![Screen Shot 2022-02-02 at 1 47 31 PM](https://user-images.githubusercontent.com/39831871/152589171-ef2cf08f-9294-4339-ba19-46df30da2df1.png)

**Details:**

- Operating System: MacOS 10.15.7
- Python 3.9.7
- glue-core 1.2.2
- glue-jupyter 0.10.1

* Not that this is proposed to be addressed in a hack day with @astrofrog

**Comment by pllim** [comment]
My hunch is that the fix involves JS black magic that is beyond me. Here is my best guess on what needs to happen: When [vue_set_color](https://github.com/glue-viz/glue-jupyter/blob/d6c9dd72714d5f3d872289bdcac5a9acc2161232/glue_jupyter/widgets/layer_options.py#L79) is called, it needs to go back to change [glue-color-menu background](https://github.com/glue-viz/glue-jupyter/blob/d6c9dd72714d5f3d872289bdcac5a9acc2161232/glue_jupyter/widgets/layeroptions.vue#L17) and things that set `subset.color` in [subset_select.vue](https://github.com/glue-viz/glue-jupyter/blob/main/glue_jupyter/widgets/subset_select.vue).

**Comment by rosteen** [comment]
For the subset selection menu, I think that triggering `_sync_available_from_state` in `subset_select_vuetify.py` would suffice - currently it's only triggered on subset creation and deletion. I'm not sure if issuing a Message to the hub from the layer options on color select would be the best plan, or if that currently does so and we're just not listening for it. 

I'm not sure about the square in the layer menu itself, I didn't have time to track down what object is populating that color in the vuetify file.
