### ISSUE TITLE
Readthedocs links to example notebooks: Binder fails to build

### ISSUE THREAD

**Issue by s-goldman** [glue-viz/glue-jupyter#285]
None of the links to binder example notebooks correctly build for the links at the bottom of the readthedocs home page. 

Tried to load a notebook using binder home page interface and the URL to a glue-viz example notebook. This gave me a more specific error in binder:
<img width="969" alt="Screen Shot 2022-02-16 at 10 41 49 AM" src="https://user-images.githubusercontent.com/32876747/154300875-9436da57-3edd-4b62-a242-35485edc2322.png">

**Comment by astrofrog** [comment]
This should be fixed now, please try the links in the README again - thanks!
