### ISSUE TITLE
Subset selection region doesn't resize properly with viewer

### ISSUE THREAD

**Issue by rosteen** [glue-viz/glue-jupyter#314]
**Describe the bug**
When a viewer is resized, if the subset selection tool is active, the gray region showing the current selected area does not resize properly, while the colored region corresponding to the finalized subset does, leaving them out of sync visually. This isn't a huge problem, just a slight annoyance. Preferably the gray and red areas in the screenshot below would both be overlapping circles. 

To replicate, draw a subset, then do something to resize the viewer (in my case, I opened our plugin tray).

There's a chance that this is specific to Jdaviz, I don't recall if we do something different than base glue-jupyter to interrupt the subset creation process so that the subset doesn't "finalize" until further action is taken (e.g. clicking off the tool).

**Screenshots**

![Screen Shot 2022-06-07 at 3 06 41 PM](https://user-images.githubusercontent.com/39831871/172485796-cf61084c-4045-430e-a969-e43086928146.png)

**Comment by maartenbreddels** [comment]
@rosteen should we make bqplot-image-gl 1.4.10 as a min requirement do you think?
