### ISSUE TITLE
get_ioloop broken with pyzmq 25.0.0

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-jupyter#342]
**Describe the bug**

```
.../glue_jupyter/utils.py:101, in get_ioloop()
     99 ipython = IPython.get_ipython()
    100 if ipython and hasattr(ipython, 'kernel'):
--> 101     return zmq.eventloop.ioloop.IOLoop.instance()

AttributeError: module 'zmq.eventloop' has no attribute 'ioloop'
```

I think `get_ioloop` should not use `pyzmq`, maybe just call asyncio directly but I am not sure on the correct implementation here.

**To Reproduce**

Try to run `glue_jupyter.utils.get_ioloop` function with `pyzmq` 25.0.0. Also see https://github.com/zeromq/pyzmq/blob/main/zmq/eventloop/ioloop.py

**Expected behavior**

No error.

**Additional context**

Works when downgraded pyzmq to 24.0.1 but this is not ideal solution.

[🐱](https://jira.stsci.edu/browse/JDAT-3043) cc @javerbukh

**Comment by maartenbreddels** [comment]
We can now use `asyncio.get_event_loop()`, `event_loop.run_until_complete(..)` instead I think. This was from a time where tornado/ipython was used, and not the Python asyncio module.
Should I take a look next week, or do you want to try? A key point would be to identify where the denounced is used, and to make sure it still works :)
