### ISSUE TITLE
show() should be optional

### ISSUE THREAD

**Issue by eteq** [glue-viz/glue-jupyter#35]
Continuing in a series of issues that are "confusing elements of the API" from work on #28 :

Right now the visualizations always get shown whenever a glupyter visualization is executed.  But there are times when it's useful to create the widget but *not* show it until it is the last line of a cell.  While I can see the merit of either way of doing it, there should be a way to control this so that it's *possible* to not get the `show()` on create beahvior

**Comment by astrofrog** [comment]
@eteq - it's now possible to set ``show=False`` when creating a viewer:

https://github.com/glue-viz/glue-jupyter/blob/master/glue_jupyter/app.py#L184

The default is still ``True`` though. Are you ok with that?

**Comment by astrofrog** [comment]
I'll go ahead and close this since I think this has been addressed
