### ISSUE TITLE
Table viewer 

### ISSUE THREAD

**Issue by martinRenou** [glue-viz/glue-jupyter#352]
**Describe the solution you'd like:**

The Glue Qt supports a table viewer, it would be nice to implement the same in Glue jupyter.

[ipydatagrid](https://github.com/bloomberg/ipydatagrid) could be a good candidate for an implementation for this:
- it uses bqplot scales by default (created and maintained by the bqplot developers)
- it has selection/filtering logic
- conditional rendering

**Comment by maartenbreddels** [comment]
FYI: There is already a table viewer in glue jupyter https://github.com/glue-viz/glue-jupyter/tree/main/glue_jupyter/table

**Comment by martinRenou** [comment]
Thanks! I've not seen it in the documentation, so I assumed it was not there.

**Comment by martinRenou** [comment]
Closing as answered
