### ISSUE TITLE
Disparity in linear scatter size between matplotlib and bqplot viewers

### ISSUE THREAD

**Issue by Carifio24** [glue-viz/glue-jupyter#392]
**Describe the bug**
The displayed sizes when using linear size mode are significantly different between the matplotlib (Qt) and bqplot viewers. In particular, I think that the matplotlib layer artist accounts for the fact that we are setting area sizes, while the bqplot layer artist doesn't.

**To Reproduce**
This could be reproduced with any data, but here are quick snippets:

In the Qt terminal:
```
from glue.core import Data
from glue_qt.viewers.scatter import ScatterViewer

x = [i for i in range(100)]
y = [i + 200 for i in range(100)]
data = Data(label='data', x=x, y=y)
dc.append(data)

viewer = application.new_data_viewer(ScatterViewer, data=data)
layer = viewer.layers[0]
layer.state.size_att = data.id['x']
layer.state.size_mode = 'Linear'
layer.state.size_vmin = 0
layer.state.size_vmax = 100
layer.state.color = '#0055ff'
layer.state.size_scaling = 2
```

In a Jupyter notebook:
```
from glue.core import Data
from glue_jupyter import jglue
from glue_jupyter.bqplot.scatter import BqplotScatterView

app = jglue()
session = app.session
dc = app.session.data_collection

x = [i for i in range(100)]
y = [i + 200 for i in range(100)]
data = Data(label='data', x=x, y=y)
dc.append(data)

viewer = app.new_data_viewer(BqplotScatterView, data=data)
layer = viewer.layers[0]
layer.state.size_att = data.id['x']
layer.state.size_mode = 'Linear'
layer.state.size_vmin = 0
layer.state.size_vmax = 100
layer.state.color = '#0055ff'
layer.state.size_scaling = 2
```

**Expected behavior**
The two plots should look basically the same. Obviously they won't look identical as we're using different frontends, but I would expect to see the same general behavior

**Screenshots**
Here's what this looks like in Qt glue:
![SizeScalingMpl](https://github.com/glue-viz/glue-jupyter/assets/14281631/41c9a5b7-09e6-44fb-967a-ef2c01af261a)

and the same thing (equivalent state values) in the bqplot viewer:
![SizeScalingBqplot](https://github.com/glue-viz/glue-jupyter/assets/14281631/4e7b505e-e35f-4867-bce2-b64e41cd8b10)

If I manually square each element of the scatter mark's size array, I get this, which looks quite similar to the matplotlib viewer:
![SizeScalingBqplot_modified](https://github.com/glue-viz/glue-jupyter/assets/14281631/6357dedf-c387-4683-8824-974785ff95c0)

**Details:**

- Operating System: Ubuntu 20.04
- Python version: 3.11.4
- Glue version: 1.13.1
- How you installed glue: pip

**Additional context**
As I mentioned above, I believe the disparity is due to the fact that the bqplot layer artist is missing an equivalent to [this line](https://github.com/glue-viz/glue/blob/main/glue/viewers/scatter/layer_artist.py#L437), as bqplot marks are also setting the area.

**Comment by astrofrog** [comment]
I agree we should fix this - do you want to open a PR?

**Comment by Carifio24** [comment]
Will do!
