### ISSUE TITLE
`runipy` EOL

### ISSUE THREAD

**Issue by dhomeier** [glue-viz/glue-jupyter#413]
**Describe the bug**
`runipy` has been [deprecated](https://github.com/paulgb/runipy#readme) and essentially unmaintained for 8 years; condaforge is not offering it for Python > 3.10, and the pip install is failing for 3.12 on outdated `configparser` usage, e.g. https://github.com/glue-viz/glue-jupyter/actions/runs/7048615523/job/19185411334?pr=412#step:7:555
**To Reproduce**
As the `publish` workflow is now executed by default in a py312 env, it is broken with the above error since.
**Additional context**
`publish` might be fixed for now by tagging it to an older Python version, but the README recommends to switch to the Jupiter execute API.

**Comment by astrofrog** [comment]
We can probably replace with papermill
