### ISSUE TITLE
3D scatter viewer broken

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-jupyter#449]
The 3D scatter viewer is no longer showing any points for me, and also shows an additional panel between the visualization and the regular glue viewer and layer options:

![image](https://github.com/glue-viz/glue-jupyter/assets/314716/e4cd3988-795c-4f48-846a-42232b2e3fcb)

@maartenbreddels - before I dig too far into this, are you aware of any changes in ipyvolume recently that might have caused this?

**Comment by astrofrog** [comment]
To hide the side panel we need https://github.com/widgetti/ipyvolume/pull/442

**Comment by Carifio24** [comment]
@maartenbreddels It must be something in how the scatter is wired up to the glue viewer (though I haven't really had time to investigate), as Azmé and I have made ipyvolume scatters that work, but then the same data won't display in glue.

**Comment by Carifio24** [comment]
@astrofrog @maartenbreddels I figured out the basic issue here . It looks like trying to make a plot where one of the x/y/z components has an underlying numpy array whose data type isn't a float won't work. And it seems to fail in a way that breaks updating the scatter widget, as changing the offending component to something that's floats doesn't fix things

As an example see [this gist](https://gist.github.com/Carifio24/dbcec0985eeef5b1ce826d350c3aa8e1). The original W5 data won't show, but if I create a new data object with non-float components removed, it renders fine. I'm not sure whether this is an ipyvolume issue (some sort of bad serialization?) or whether we need to do some `astype`-ing in the layer artist.
