### ISSUE TITLE
merge fails for py27

### ISSUE THREAD

**Issue by maartenbreddels** [glue-viz/glue-jupyter#52]
If I load a dataset twice, I tries merging them, which fails in this test for py27:
https://travis-ci.org/glue-viz/glue-jupyter/jobs/451897536
I'm gonna skip that test, because I don't think it's something I should test, but reporting if so it does not get lost.

**Comment by astrofrog** [comment]
Fixed in https://github.com/glue-viz/glue-jupyter/pull/51 (I hope)

**Comment by astrofrog** [comment]
I'm going to close this since it should  be fixed, and we're going to drop Python 2 support anyway (https://github.com/glue-viz/glue-jupyter/issues/46)
