### ISSUE TITLE
Have default attributes for viewers

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-jupyter#6]
For the histogram viewer, if no attribute is specified, we should just pick the first one. For the scatter viewer, we should pick the first two (or twice the first one if there is only one attribute). And so on.

**Comment by maartenbreddels** [comment]
I think this is all implemented, all arguments to app.scatter/plot etc are optional, is that what was meant here?

**Comment by astrofrog** [comment]
@maartenbreddels - yes, that's correct, thanks!
