### ISSUE TITLE
Implement support for square pixel aspect ratio in image viewer

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-jupyter#9]
Currently the image viewer doesn't constrain the aspect ratio of pixels:

<img width="749" alt="screen shot 2018-08-26 at 12 53 34" src="https://user-images.githubusercontent.com/314716/44630654-25f26600-a92f-11e8-9160-d0e2e07349d7.png">

It would be nice to support this to avoid 'squashed' images.

**Comment by maartenbreddels** [comment]
In principle, an aspect of 1 would work, even without the referenced fix. Do you see a use case for aspect != 1?

**Comment by astrofrog** [comment]
@maartenbreddels - I don't see any use case for a fixed aspect != 1, but we do want to allow the 'auto' aspect mode meaning the image just fills the axes (the current behavior), as this is useful when the image isn't a 'spatial' image (e.g. a PV diagram).

**Comment by maartenbreddels** [comment]
yeah, so a checkbox/toggle button with 'equal aspect' would do right?

**Comment by astrofrog** [comment]
@maartenbreddels - yep!

**Comment by maartenbreddels** [comment]
Solved by #40
