### ISSUE TITLE
2D image not showing with voila

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-jupyter#94]
I am not sure if this is the best place to open this issue but it is the best I can think of. I found that the 2D image display works if a notebook is run as a normal Jupyter notebook but does not show anything if it is run with [voila](https://github.com/QuantStack/voila). No traceback seen on terminal. Notebook available from spacetelescope/dat_pyinthesky#58

cc @astrofrog

**Comment by astrofrog** [comment]
I've run into this a few times, and it seems to be related to https://github.com/bloomberg/bqplot/issues/856, so I'll just close this since there's nothing we can do here about it.

**Comment by maartenbreddels** [comment]
Can you check if you see an error on the javascript console next time this happens, if so, please share it here.

**Comment by pllim** [comment]
```
Kernel: kernel_ready (...)
TypeError: model.state_change is undefined (manager-base.js:90)
THREE.WebGLRenderer 91 (three.module.js:21158)
TypeError: model.state_change is undefined (manager-base.js:90)
ImageGLView.data is a Float64Array which WebGL does not support, will convert to a Float32Array (consider sending float32 data for better performance). (imagegl.js:263)
```

**Comment by pllim** [comment]
In a different run, the image shows and I still see the same kind of messages in dev console. :woman_shrugging:
